apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy-s2 # tomcat
  labels:
    app: nginx # tomcat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx # tomcat
  template:
    metadata:
      labels:
        app: nginx # tomcat
    spec:
      containers:
      - name: nginx # tomcat
        image: nginx:1.21 # tomcat:9.0
        ports:
        - containerPort: 80

