apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx121-deployment-steed2 # tomcat
  labels:
    app: nginx121 # tomcat
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx121 # tomcat
  template:
    metadata:
      labels:
        app: nginx121 # tomcat
    spec:
      containers:
      - name: nginx121 # tomcat
        image: nginx:1.21 # tomcat:9.0
        ports:
        - containerPort: 80

